# version: '3'
# services:
#   postgresql:
#     container_name: 'in_the_eyes_postgresql'
#     image: postgres:11.0-alpine
#     ports:
#       - '5432:5432'
#     volumes:
#       - ./data/postgresql:/var/lib/postgresql/data
#   app: &app_base
#     container_name: 'in_the_eyes_app'
#     build: .
#     command: bundle exec puma -C config/puma-production.rb
#     volumes:
#       - ./etc/nginx/conf.d:/etc/nginx/conf.d
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgresql
#     environment:
#       - RAILS_ENV=production
#       - DATABASE_URL=postgres://postgres@postgresql:5432
#   web:
#     <<: *app_base
#     container_name: 'in_the_eyes_web'
#     links:
#       - app
#     command: /etc/nginx/start
#     ports:
#       - "80:80"

version: '3'
volumes:  
  postgres_data: {} 
services:  
  app:    
    container_name: 'in_the_eyes_app'
    build:      
      context: .
      dockerfile: ./docker/DockerFile-app
    depends_on:      
      - db  
  db:    
    container_name: 'in_the_eyes_db'
    image: postgres    
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
  web:    
    container_name: 'in_the_eyes_web'
    build:      
      context: .
      dockerfile: ./docker/DockerFile-web
    depends_on:      
      - app    
    ports:      
      - 80:80