version: '3'
volumes:  
  postgres_data: {} 
  public: 
  redis_data:
services:  
  app:    
    container_name: 'in_the_eyes_app'
    volumes:      
       - public:/home/app/in_the_eyes/public
    image: in_the_eyes_app_image:latest
    links:      
      - db  
      - redis_db  
  db:    
    container_name: 'in_the_eyes_db'
    image: postgres    
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
  web:    
    container_name: 'in_the_eyes_web'
    volumes:      
       - public:/home/app/in_the_eyes/public
    build:      
      context: .
      dockerfile: ./docker/DockerFile-web
    links:      
      - app    
    ports:      
      - 80:80
  redis_db:
    image: 'redis:4.0-alpine'
    command: redis-server #--requirepass yourpassword
    volumes:
      - 'redis_data:/data'