version: '3'
volumes:  
  postgres_data: {} 
  public: 
services:  
  app:    
    container_name: 'in_the_eyes_app'
    volumes:      
       - public:/home/app/in_the_eyes/public
    image: in_the_eyes_app_image:latest
    links:      
      - db  
  db:    
    container_name: 'in_the_eyes_db'
    image: postgres    
    volumes:      
      - postgres_data:/var/lib/postgresql/data  
  web:    
    container_name: 'in_the_eyes_web'
    volumes:      
       - public:/home/app/in_the_eyes/public
    build:      
      context: .
      dockerfile: ./docker/DockerFile-web
    links:      
      - app    
    ports:      
      - 80:80