#!/bin/bash
if [ -z ${IMAGE_VERSION+x} ];then
  IMAGE_VERSION=latest
fi

image_name="in_the_eyes_app_image"
version=$(date "+%Y%m%d%H%M%S")
current_version=$IMAGE_VERSION

docker build -f docker/DockerFile-app -t $image_name .
docker tag $image_name:$current_version $image_name:$version

echo $version > .previous-version