#!/bin/bash
if [ -z ${IMAGE_VERSION+x} ];then
  IMAGE_VERSION=latest
fi

image_name="in_the_eyes_app_image"
version=$(date "+%Y%m%d%H%M%S")
current_version=$IMAGE_VERSION

cd app_code &&\
	git checkout master &&\
	git pull &&\
	docker build -f docker/DockerFile-app -t $image_name . &&\
	docker tag $image_name:$current_version $image_name:$version &&\
	echo $version > .previous-version &&\
	docker-compose stop app &&\
	docker-compose up -d app &&\
	docker-compose run app bundle exec rake assets:precompile RAILS_ENV=production
	docker-compose run app bundle exec rails db:migrate RAILS_ENV=production